### ISSUE TITLE
cheerlights.py cannot show yellow

### ISSUE THREAD

**Issue by alexellis** [pimoroni/blinkt#23]
Try it out.. it won't show yellow for us. @Gadgetoid

**Comment by Gadgetoid** [comment]
I don't think Cheerlights supports yellow. They must have gone MVP and omitted yellow to save on development time :P

Despite having Tweeted yellow, it's just not in their feed:

http://api.thingspeak.com/channels/1417/feed.json

This is something that'll need fixing by the Cheerlights creator.

**Comment by dglaude** [comment]
Maybe it is "Amber"?
GPIO Zero made a mess with the traffic light colour (color) naming.
Maybe Cheerlights is doing the same?

2016-08-05 16:53 GMT+02:00 Philip Howard notifications@github.com:

**Comment by Gadgetoid** [comment]
This was a bug in cheerlights API itself. It's now, as far as I know, fixed!
