### ISSUE TITLE
I created another third-party library

### ISSUE THREAD

**Issue by HoldYourWaffle** [pimoroni/blinkt#66]
#### (I'm sorry if this isn't the right way to contact you guys for this)

I created a new Blinkt java api using hackerjimbo's existing library, but stripping away the generalisations(/bloat) for other LED boards. You can find it [here](https://github.com/HoldYourWaffle/blinkt4j).
I would greatly appreciate it if you added it to the list in the readme 😄

**Comment by Gadgetoid** [comment]
It's as good a way as any! Thank you for bringing it to my attention. I've added a link.
