### ISSUE TITLE
python3-blinkt package hasn't installed python3 module

### ISSUE THREAD

**Issue by martinohanlon** [pimoroni/blinkt#71]
I have run the blinkt installation and apt reports that the `python3-blinkt` package has been installed but `blinkt` cannot be imported by python 3. python 2 works fine.

![image](https://user-images.githubusercontent.com/2329501/50551337-e63de100-0c76-11e9-8e12-4250804b2c05.png)

**Comment by martinohanlon** [comment]
Fyi - I had to install `blinkt` using `pip3` to get it to work.

![image](https://user-images.githubusercontent.com/2329501/50551388-88f65f80-0c77-11e9-8df6-0440de74ce85.png)

**Comment by Gadgetoid** [comment]
I see this from time to time and it often indicates a corrupt package install- I don't know if that was the case in this specific instance. Glad you're up and running though.
