### ISSUE TITLE
RuntimeError: Not running on a RPi! on DietPi

### ISSUE THREAD

**Issue by ghost** [pimoroni/blinkt#85]
The title pretty much. I use DietPi and it shows this error. Raspberry Pi 4B+.

```
dietpi@raspi:~/Pimoroni/blinkt/examples$ python3 cpu_load.py 
Traceback (most recent call last):
  File "cpu_load.py", line 31, in <module>
    show_graph(v, 255, 255, 255)
  File "cpu_load.py", line 25, in show_graph
    blinkt.show()
  File "/usr/lib/python3/dist-packages/blinkt.py", line 76, in show
    GPIO.setup(DAT, GPIO.OUT)
RuntimeError: Not running on a RPi!
```

**Comment by druck13** [comment]
On 09/05/2020 11:28, gogotz wrote:
> The title pretty much. I use DietPi and it shows this error. Raspberry 
> Pi 4B+.
> 
> |dietpi@raspi:~/Pimoroni/blinkt/examples$ python3 cpu_load.py Traceback 
> (most recent call last): File "cpu_load.py", line 31, in <module> 
> show_graph(v, 255, 255, 255) File "cpu_load.py", line 25, in show_graph 
> blinkt.show() File "/usr/lib/python3/dist-packages/blinkt.py", line 76, 
> in show GPIO.setup(DAT, GPIO.OUT) RuntimeError: Not running on a RPi! |

This might help https://github.com/adafruit/Adafruit_Blinka/issues/150

Cheers
---David
-- 
Email: druck@druck.org.uk
Phone: +44-(0)7974 108301

**Comment by ghost** [comment]
Adding the user to the `gpio` group fixed the issue, thank you!
