### ISSUE TITLE
Cannot reference blinkt from Python3 / Arm64

### ISSUE THREAD

**Issue by ElSrJuez** [pimoroni/blinkt#87]
Issue: I am trying out the python samples on my pimoroni blinkt! but I am getting the following error:
**ModuleNotFoundError: No module named 'blinkt'**

I am using python3 under ubuntu server 20.04 arm64 from a Raspberry Pi 4.

I would like to know how to make this work?

**Comment by druck13** [comment]
On 13/07/2020 18:24, Diego Vásquez wrote:
> Issue: I am trying out the python samples on my pimoroni blinkt! but I 
> am getting the following error:
> *ModuleNotFoundError: No module named 'blinkt'*
> 
> I am using python3 under ubuntu server 20.04 arm64 from a Raspberry Pi 4.
> 
> I would like to know how to make this work?

As you aren't using Raspbian, you may need to try the manual 
installation procedure here https://github.com/pimoroni/blinkt rather 
than relying on simple install script.

Make sure you install both Python 2 and Python 3 variants, so the blinkt 
library can be used from either.

Cheers
---David
