### ISSUE TITLE
Question: native SPI vs software SPI

### ISSUE THREAD

**Issue by natcl** [pimoroni/blinkt#93]
I noticed the Blinkt doesn't use the native SPI ports of the PI and I was wondering if there was a technical reason for this ?

Thanks !

**Comment by Gadgetoid** [comment]
Yes, but it would be lost to the river of time. There's probably some legacy reason to maintain compatibility with a display product, but IMHO bit-banging the APA102 protocol is more fun 😆 and of more educational value. This is, perhaps, more an accidental than intentional upside though!

**Comment by natcl** [comment]
Make sense !
Thanks for satisfying my curiosity :)
